### ISSUE TITLE
vast.ai error

### ISSUE THREAD

**Issue by x319x** [acids-ircam/RAVE#148]
i am trying to run rave on vast.ai. however if i run it via a notebook or via the CLI i get the following error:

Traceback (most recent call last):
  File "/workspace/RAVE/train_rave.py", line 156, in <module>
    nepoch = args.VAL_EVERY // len(train)
ZeroDivisionError: integer division or modulo by zero

i followed the instructions + ran these two commands as it couldnt find the sndfile otherwise
sudo apt-get update
sudo apt-get install libsndfile1

how can we solve this? it would be great if we could run RAVE on vast.ai, it would be cheaper and if desired also faster.
thanks.

**Comment by domkirke** [comment]
Your dataset is empty (probably not long enough). Try with a bigger dataset!
