### ISSUE TITLE
question about loudness based loss

### ISSUE THREAD

**Issue by faroit** [acids-ircam/RAVE#151]
https://github.com/acids-ircam/RAVE/blob/54c6106eca9760041e7d01e10ba1e9f51f04fc5a/rave/core.py#L130

I understand that the loudness based distance is just an approximation but I wonder why its added to the log spectrogram instead of mulitplying. Furthermore, what about using a time-domain prefilter as implemented by @csteinmetz1:

https://github.com/csteinmetz1/auraloss/blob/e732234398ada867138be634dbf66f40360461a2/auraloss/perceptual.py#L124-L129

and then implement it like:

```python
mse(self.log_stft(time_domain_prefilter(x)), self.log_stft(time_domain_prefilter(y)))
```

can you comment on some pro and cons of either way?

**Comment by domkirke** [comment]
in this code a_weight are also in db, such that the multiplications becomes an addition.

**Comment by faroit** [comment]
@domkirke ahhh... missed that 🤦 thanks
