### ISSUE TITLE
No such file or directory error in rave preprocess

### ISSUE THREAD

**Issue by schmolmo** [acids-ircam/RAVE#160]
Hey there,

I just freshly installed RAVE V2 (congrats, btw!) on my M2 MacBook Air, when I'm running 

`(rave2) moritz@Air-von-Moritz ~ % rave preprocess --input_path /Users/moritz/Downloads/sax01_data_44100_raw  --sampling_rate  48000 --output_path /Users/moritz/Documents/Projekte/2212\ rave\ hans/v2/db   --max_db_size 5 
`
I get this prompt and the terminal freezes: 
`0it [00:00, ?it/s](FileNotFoundError(2, 'No such file or directory'),)`

The directories both exist, I double checked :-) 

Any ideas? Also, I had to manually install torchaudio via pip, it wasn't install when I `pip install acids-rave` in a fresh conda env 

All best,
schmolmo

**Comment by caillonantoine** [comment]
Hi, I have added torchaudio + ffmpeg to the requirement list, thanks ! However regarding your problem I'm not sure how to based only on this error... + Training on a macbook air might not be the best option !

**Comment by 50NNY1** [comment]
the issue is you are running the command whilst inside a directory which cannot see the 'dataset' directory. Cd back to your root directory and it will work absoloutely fine.

**Comment by caillonantoine** [comment]
I'm not sure that this is the issue, as the path are both absolute. Can you check you have `ffmpeg` installed ?

**Comment by schmolmo** [comment]
Installing ffmpeg as in the README solved the issue, thank you! :~)
