### ISSUE TITLE
Error when exporing RAVE v2

### ISSUE THREAD

**Issue by moiseshorta** [acids-ircam/RAVE#163]
Hi,

I seem to be running into this error when exporting RAVE with v2 config:

`AttributeError: module 'rave.blocks' has no attribute 'GRU'`

I have to note that the model hasn't finished training completely, but wanted to test if it's possible to export. 
Is the basic 2 phase training schedule preserved for v2? does this module get added when going into phase 2?

**Comment by caillonantoine** [comment]
Good catch ! I'll look at that asap

**Comment by caillonantoine** [comment]
Should be fixed now !

**Comment by moiseshorta** [comment]
Works now!

**Comment by moiseshorta** [comment]
UPDATE: I just tested the exported RAVE v2 .ts and even though it loads into nn~, it doesn't output any audio.

Dunno if to post this to nn~ repo or here...

**Comment by moiseshorta** [comment]
Export works, but when trying to perform timbre transfer with RAVE v2 and nn~, there is no sound.

 Not sure if to post this in nn~ or here...
