### ISSUE TITLE
No audio coming out of exported RAVE v2 in nn~

### ISSUE THREAD

**Issue by moiseshorta** [acids-ircam/RAVE#164]
Hi,

I've successfully been able to export the model as a torchscript file. The loading into nn~ has no errors, however, there is no audio coming out when passing a signal through the encode/decode function.

I'm not sure if to post this issue here or in nn~ repo.

**Comment by caillonantoine** [comment]
Make sure your training PyTorch version is lower or equal to the one nn~ uses !

**Comment by moiseshorta** [comment]
I tried and updated the pytorch version with the latest nn~ version and this did work when training a model with the V2/Wasserstein config. 

However it did not work when I trained the V2/Default config. I also mention in this issue that that when using this config (V2/Default) there is only one latent space dimension when exporting as .ts.

I have to add that both worked when doing offline timbre transfer in Python.
