### ISSUE TITLE
ffmpeg dependency

### ISSUE THREAD

**Issue by schramm** [acids-ircam/RAVE#166]
The new version/current state looks awesome. 

I notice the new README.md  has no mention about FFMPEG dependency.  If not installed, the preprocessing script will get stuck and no output will be generated. Even worst, for me, I didn't get any error in the terminal output.  

After ffmpeg get installed in my system (apt install ffmpeg), the problem was solved. Maybe it would be nice to have a line in the README about ffmpeg.

**Comment by caillonantoine** [comment]
Good point thanks ! I'll add that asap

**Comment by caillonantoine** [comment]
Done :)
