### ISSUE TITLE
some question about training procedure

### ISSUE THREAD

**Issue by gyuchulm** [acids-ircam/RAVE#170]
I've trained the model in Google Colab, but now I am training locally. 
I have some questions about the training stage. (anaconda prompt environment)

1. how to stop epoch while training? 
2. In Colab, while training, It can check the model while training, but in the prompt, 
how to validate the model? Is it possible to check the status while training?

**Comment by materialvision** [comment]
Hi, if you train locally you must run tensorboard, ex. tensorboard --logdir . --bind_all while in the RAVE folder. Then you can check the status in a browser.
