### ISSUE TITLE
model has 127 latent dimension inn nn_tilde

### ISSUE THREAD

**Issue by alex-frx** [acids-ircam/RAVE#181]
Why does my model have so many dimesions? i thought i could be 16 max?

**Comment by caillonantoine** [comment]
Hi,

What configuration are you using ?

**Comment by alex-frx** [comment]
Im using v2. But my training did not went in second phase. Maybe thats why? Can i mannually start the second phase?

**Comment by caillonantoine** [comment]
What fidelity value are you using ?

**Comment by alex-frx** [comment]
I did not set it explicitly so the default value probably. 
what exactly doe it change? 
im ne to ai but have a computer science background sorry if some questions are very basic. im trying to find as much infos about rave as i can

**Comment by alex-frx** [comment]
maybe connected to #188

**Comment by caillonantoine** [comment]
So you did choose the Wasserstein regularization ?

**Comment by alex-frx** [comment]
I am not sure anymore atm to be honest.  
I thought I choose v2  // default. 
I started training another model over night (its still training) but in the tensorboard under fidelity I see now around 4-8  dimensions. which is nice 

---
sorry for the confusion

**Comment by materialvision** [comment]
I also tested the Wassertein regularization and got 127 latent dimensions (or a lot) in nn. It might be a bug?

**Comment by caillonantoine** [comment]
Yes I used to manually override the latent size when using the wasserstein regularization (`--override LATENT_SIZE=16`). I have set the default latent size for the wasserstein mode to 16 now !

**Comment by materialvision** [comment]
> Yes I used to manually override the latent size when using the wasserstein regularization (`--override LATENT_SIZE=16`). I have set the default latent size for the wasserstein mode to 16 now !

Thanks for that, but I still get the same problem in Max with nn~ having far too many outlets and inlets... Tested both with the --override LATENT_SIZE method and with your latest change of the default. 

Here is some of the printed debug info when I start training: 

`rave train --config v2 --config was
sertein --db_path ~/data/usrinind/proc --name usrinindwass12 --ckpt ~/RAVE/runs/
usrinindwass12_24574138f3
I0215 09:36:03.531806 140215438332288 resource_reader.py:50] system_path_file_ex
ists:v2.gin
E0215 09:36:03.532041 140215438332288 resource_reader.py:55] Path not found: v2.
gin
I0215 09:36:03.532118 140215438332288 resource_reader.py:50] system_path_file_ex
ists:/home/deepbek/miniconda3/envs/ravev2/lib/python3.9/site-packages/rave/v2.gi
n
E0215 09:36:03.532160 140215438332288 resource_reader.py:55] Path not found: /ho
me/deepbek/miniconda3/envs/ravev2/lib/python3.9/site-packages/rave/v2.gin
I0215 09:36:03.532758 140215438332288 resource_reader.py:50] system_path_file_ex
ists:configs/v1.gin
E0215 09:36:03.532924 140215438332288 resource_reader.py:55] Path not found: con
figs/v1.gin
I0215 09:36:03.545935 140215438332288 resource_reader.py:50] system_path_file_ex
ists:wassertein.gin
E0215 09:36:03.546091 140215438332288 resource_reader.py:55] Path not found: was
sertein.gin
I0215 09:36:03.546174 140215438332288 resource_reader.py:50] system_path_file_ex
ists:/home/deepbek/miniconda3/envs/ravev2/lib/python3.9/site-packages/rave/wasse
rtein.gin
E0215 09:36:03.546257 140215438332288 resource_reader.py:55] Path not found: /ho
me/deepbek/miniconda3/envs/ravev2/lib/python3.9/site-packages/rave/wassertein.gi
n
RAVE(
  (pqmf): CachedPQMF(
    (forward_conv): Conv1d(1, 16, kernel_size=(513,), stride=(16,), bias=False)
    (inverse_conv): Conv1d(16, 16, kernel_size=(33,), stride=(1,), bias=False) 
  )
  (encoder): WasserteinEncoder(
    (encoder): Encoder(
      (net): CachedSequential(
        (0): Conv1d(16, 96, kernel_size=(7,), stride=(1,), bias=False)
        (1): BatchNorm1d(96, eps=1e-05, momentum=0.1, affine=True, track_running
_stats=True)
        (2): LeakyReLU(negative_slope=0.2)
        (3): Conv1d(96, 192, kernel_size=(9,), stride=(4,), bias=False)
        (4): BatchNorm1d(192, eps=1e-05, momentum=0.1, affine=True, track_runnin
g_stats=True)
        (5): LeakyReLU(negative_slope=0.2)
        (6): Conv1d(192, 384, kernel_size=(9,), stride=(4,), bias=False)
        (7): BatchNorm1d(384, eps=1e-05, momentum=0.1, affine=True, track_runnin
g_stats=True)
        (8): LeakyReLU(negative_slope=0.2)
        (9): Conv1d(384, 768, kernel_size=(9,), stride=(4,), bias=False)
        (10): BatchNorm1d(768, eps=1e-05, momentum=0.1, affine=True, track_runni
ng_stats=True)
        (11): LeakyReLU(negative_slope=0.2)
        (12): Conv1d(768, 1536, kernel_size=(5,), stride=(2,), bias=False)
        (13): LeakyReLU(negative_slope=0.2)
        (14): Conv1d(1536, 128, kernel_size=(5,), stride=(1,), bias=False)
      )
    )
  )
  (decoder): GeneratorV2(

[skipped to the end here]

  | Name                     | Type                  | Params
-------------------------------------------------------------------
0 | pqmf                     | CachedPQMF            | 16.7 K
1 | encoder                  | WasserteinEncoder     | 10.4 M
2 | decoder                  | GeneratorV2           | 17.8 M
3 | discriminator            | CombineDiscriminators | 27.1 M
4 | audio_distance           | AudioDistanceV1       | 0
5 | multiband_audio_distance | AudioDistanceV1       | 0
-------------------------------------------------------------------
`

**Comment by caillonantoine** [comment]
The `--LATENT_SIZE` flag needs to be set during training. You are still using a latent size of 128, cf your last encoder layer `(14): Conv1d(1536, 128, kernel_size=(5,), stride=(1,), bias=False)`

**Comment by devstermarts** [comment]
@caillonantoine To clarify: using `--override LATENT_SIZE=16` is a _must_ when training using Wasserstein and not a _default_ setting, correct? Your change from commit 9873c1e doesn't automatically set the number of latent dimensions to 16?

I was starting a training yesterday after pulling the latest version of RAVE without setting the flag which resulted also in nn~ with lots of in-/outlets as mentioned by @materialvision. Setting `--override LATENT_SIZE=16` in a training that's currently running results in the following (which seems OK). 

  ```
(encoder): WasserteinEncoder(
    (encoder): Encoder(
      (net): CachedSequential(
        (0): Conv1d(16, 96, kernel_size=(7,), stride=(1,), bias=False)
        (1): BatchNorm1d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): LeakyReLU(negative_slope=0.2)
        (3): Conv1d(96, 192, kernel_size=(9,), stride=(4,), bias=False)
        (4): BatchNorm1d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (5): LeakyReLU(negative_slope=0.2)
        (6): Conv1d(192, 384, kernel_size=(9,), stride=(4,), bias=False)
        (7): BatchNorm1d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (8): LeakyReLU(negative_slope=0.2)
        (9): Conv1d(384, 768, kernel_size=(9,), stride=(4,), bias=False)
        (10): BatchNorm1d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (11): LeakyReLU(negative_slope=0.2)
        (12): Conv1d(768, 1536, kernel_size=(5,), stride=(2,), bias=False)
        (13): LeakyReLU(negative_slope=0.2)
        (14): Conv1d(1536, **16**, kernel_size=(5,), stride=(1,), bias=False)
```
