### ISSUE TITLE
Brief explanation on the difference between regularizations

### ISSUE THREAD

**Issue by moiseshorta** [acids-ircam/RAVE#188]
Hi,

I've been experimenting with the different regularization configs and thought to share some insights, at least between Wasserstein and ELBO (default).

ELBO seems to work very well on very homogenous datasets, but has a hard time converging when the dataset is more complex, such as full songs, leaving out characteristics of the dataset. The dimensionality reduction in latent space is a bit more interpretable, at least in my experiments, where each dimension is more or less easily identifieable on the feature it controls. I.E. first latent dimensions control more coarse features such as loudness and overall tone.

Wasserstein works extremely well on very complex datasets (full songs, even in different genres), generating good results in very few steps. The drawback is that the latent space is a bit more entangled, meaning that each dimension is way less interpretable. I can imagine that the latent manifold could be disentangled using a supervised ML method in order to navigate between more interpretable features that one selects. Also, it seems that the default size of the latent space is always 128 dimensions, at least in a couple of experiments I've done, it does not get cropped as in the ELBO regularization.

I've yet to try the Spherical regularization, so cannot comment much on this.

These explanations are mostly based on intuitive trial and error experiments, but wanted to share them to see if these intuitions are in line with the literature.

**Comment by futorio** [comment]
So the standard ELBO is good for dimension manipulation, but the Wasserstein is good for encoding and decoding complex signals.

**Comment by caillonantoine** [comment]
The size of the latent space can be set using `--override LATENT_SPACE=16ˋ !
