### ISSUE TITLE
preprocess stuck on vast.ai

### ISSUE THREAD

**Issue by x319x** [acids-ircam/RAVE#190]
hi, i wanted to run the new v2, however the preprocessing doesnt really work / it gets stuck. 

(also libdsndfile was missing which i installed via: conda install -c conda-forge libsndfile )

so when i run the preprocess script, it gets stuck as in the pic attached. running it in lazy mode gets me a bit further as it seems to at least produce the metadata file, however it also doesnt really seem to process anything and i still cannot start the training.

any idea?

![Bildschirmfoto 2023-02-09 um 17 42 26](https://user-images.githubusercontent.com/120024841/218163404-aebb846e-a150-4fbf-b51c-0ed9f00b5e17.png)

**Comment by caillonantoine** [comment]
Do you have ffmpeg installed ?

**Comment by x319x** [comment]
yes i have

**Comment by x319x** [comment]
when it stuck, this is what it produces in the dataset folder

![Bildschirmfoto 2023-02-10 um 19 45 15](https://user-images.githubusercontent.com/120024841/218172728-5b6421e2-1521-4adb-ac8e-86b1490e7f7e.png)

**Comment by x319x** [comment]
when i run the lazy version, it finishes the process, the dataset folder then looks like this 
![Bildschirmfoto 2023-02-10 um 20 08 34](https://user-images.githubusercontent.com/120024841/218177097-bd5fba74-35f2-46c2-a033-728332215054.png)

however i get these here...
![Bildschirmfoto 2023-02-10 um 20 10 09](https://user-images.githubusercontent.com/120024841/218177325-3878218a-5790-43d3-b7d5-3ee27e6a7d37.png)
![Bildschirmfoto 2023-02-10 um 20 10 42](https://user-images.githubusercontent.com/120024841/218177393-badb8102-84a7-4335-a5c6-52bff41ec17b.png)

**Comment by gyuchulm** [comment]
I don't know the exact solution to this, but It could be a temporary solution. you look into a v2.gin in rave folders; it is in the "configs" folder in it. Some procedure doesn't matter in finding the location of .gin files, but I tried in Colab; it also doesn't can't find the v2.gin file. So look into this folder, and move the v2.gin outside of the "configs" folder.

**Comment by amirpashamobinitehrani** [comment]
I had a similar issue training on Colab. It was due to my directory naming. Intuitionally I realised that the code is sensitive to spaces between folder names, a phenomena usually overlooked and ignored on Colab. So I made sure there aren't any;
for instance: 
"/contents/drive/data set/" ---> "contents/drive/dataset".

Hope that helps

**Comment by trian-gles** [comment]
Any updates on this?

**Comment by domkirke** [comment]
A preprocess "stuck" at 0 means that no audio file in the input path is long enough to be pre-processed by RAVE. I will add a FAQ in the README.md ;-)

**Comment by 11x319** [comment]
if i remember correctly the issue came from not being in the right root directory / not having the right data path or something similar
