### ISSUE TITLE
Run configurations destination for exporting is missing

### ISSUE THREAD

**Issue by jacklion710** [acids-ircam/RAVE#203]
Finished training and I'm finally ready to move onto exporting the model. Problem is that I can't find it. I assume it's in RAVE>runs>[output_name]. I found the folder named after the name I gave in the train step:

`rave train --config v2 --gpu 0 --db_path C:\Users\Jake\Desktop\Dataset --name jl-sounds-study`
path to run:
`C:\Users\Jake\miniconda3\envs\myrave\RAVE\runs\jl-sounds-study_ef5d81d6ce`

I notice the folder name has a string of seemingly random characters following it. Did I miss something or am I looking in the wrong place?

```
(myrave) C:\Windows\system32>rave export --run C:\Users\Jake\miniconda3\envs\myrave\RAVE\runs\jl-sounds-study_ef5d81d6ce (--streaming)
INFO:root:library loading
INFO:root:DEBUG
C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
I0227 17:21:33.677906 95824 export.py:206] building rave
I0227 17:21:33.677906 95824 resource_reader.py:50] system_path_file_exists:C:\Users\Jake\miniconda3\envs\myrave\RAVE\runs\jl-sounds-study_ef5d81d6ce\config.gin
E0227 17:21:33.678906 95824 resource_reader.py:55] Path not found: C:\Users\Jake\miniconda3\envs\myrave\RAVE\runs\jl-sounds-study_ef5d81d6ce\config.gin
Traceback (most recent call last):
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jake\miniconda3\envs\myrave\Scripts\rave.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\scripts\main_cli.py", line 32, in main
    app.run(export.main)
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\scripts\export.py", line 208, in main
    gin.parse_config_file(os.path.join(FLAGS.run, "config.gin"),
  File "C:\Users\Jake\miniconda3\envs\myrave\lib\site-packages\gin\config.py", line 2457, in parse_config_file
    raise IOError(err_str.format(config_file, prefixes))
OSError: Unable to open file: C:\Users\Jake\miniconda3\envs\myrave\RAVE\runs\jl-sounds-study_ef5d81d6ce\config.gin. Searched config paths: [''].
```

**Comment by devstermarts** [comment]
The string after the training's name is expected, i think. The runs folder should contain a commit file, a config.gin and "version_X" folders for all resumed training sessions with each a checkpoint folder with best.ckpt and last.ckpt files as well as a hparams.yaml file and a events.out.tfevents.<...> file. Does that help to narrow it down?

**Comment by jacklion710** [comment]
> The string after the training's name is expected, i think. The runs folder should contain a commit file, a config.gin and "version_X" folders for all resumed training sessions with each a checkpoint folder with best.ckpt and last.ckpt files as well as a hparams.yaml file and a events.out.tfevents.<...> file. Does that help to narrow it down?

Thanks for filling me in on that info. Unfortunately none of those files are present there as the runs folder folder located at C:\Users\Jake\miniconda3\envs\myrave\RAVE\runs\jl-sounds-study_ef5d81d6ce is empty. I believe something went wrong that caused these files to either disappear or never get created in the first place. more specifically, jl-sounds-study_ef5d81d6ce is the only folder in the runs folder. This is where I suspect those files you mentioned would be but they are definitely not there

**Comment by devstermarts** [comment]
@jacklion710 did you search the rest of your drive already? The folders and files are usually created in the directory you're running 'rave train' from, e.g. if you run it from the root folder of C, you should find 'status' and 'runs' folders at C:\status and C:\runs respectively.

**Comment by jacklion710** [comment]
@devstermarts I ran it in a miniconda virtual environment as an administrator. In C:\Users\Jake\miniconda3\envs\myrave\RAVE\status I found data.mdb and lock.mdb and in C:\Users\Jake\miniconda3\envs\myrave\RAVE\runs I found a folder named jl-sounds-study_ef5d81d6ce but there is nothing inside of that folder. Seems like it went missing somehow.
