### ISSUE TITLE
What is the size of the latent space?

### ISSUE THREAD

**Issue by ashesfall** [acids-ircam/RAVE#218]
When encoding audio to the latent space I see values approximately in the range -5 to +5. Is there a way to know the specific size of the latent space?

**Comment by domkirke** [comment]
The latent space is supposed to be a unit normal, such that most of the information is between -3 and 3. However :
- most of the times, the latent space is not correctly normalized. 
- if you use the model in nn~, you control the PCA of the latent space  ; the playable range is then different.

The only way to exactly know the range is then either to analyze the latent distribution of your training examples, or to try it by hand (out-of-distribution ranges are not automatically bad!).
