### ISSUE TITLE
ONNX Export Error

### ISSUE THREAD

**Issue by amirpashamobinitehrani** [acids-ircam/RAVE#225]
Hi there! After the training V2 for somewhat 3M iterations, I am trying to export an onnx version directly from the "run" directory and I am receiving this error: 

**RuntimeError: The size of tensor a (54) must match the size of tensor b (52) at non-singleton dimension 2**

Tracing back the issue I realised the problem arises from **x_net** and **x_res** sum operation in the **Residual** class:
x_net Shape: torch.Size([1, 256, 54])
x_res Shape: torch.Size([1, 256, 52])

Below, I have attached the zipped config file and also a screenshot from the error . Any Idea where this shape mis-match is coming from?
[rave_onnx_expError.zip](https://github.com/acids-ircam/RAVE/files/11129321/rave_onnx_expError.zip)

**Comment by caillonantoine** [comment]
Have you used the onnx configuration ?

**Comment by amirpashamobinitehrani** [comment]
I passed in CAPACITY = 32 and blocks.Generator.use_noise = False (included inside onnx.gin) using --override flag to the training script. That said, this is not unique to V2, also having a similar problem with another a couple of v1 trained models. 

All models easily convert to torchscript both in streaming and non-streaming mode. I get the same error when trying to convert the streaming .ts file to onnx. The non-streaming .ts converts just fine, but when loaded loaded for real-time inference, it brings those artefacts and repetitive clicks with it in silent mode.

**Comment by robclouth** [comment]
@amirpashamobinitehrani did you manage to get onnx exported models working correctly? I'm just getting noise. with v2.
