### ISSUE TITLE
Error for export

### ISSUE THREAD

**Issue by m3da9ti** [acids-ircam/RAVE#233]
Hey guys, when I want to export I get this error in colab:

```
INFO:root:library loading
INFO:root:DEBUG
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpqpdnj00u
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpqpdnj00u/_remote_module_non_scriptable.py
I0602 15:05:06.325452 140041712489280 export.py:255] building rave
I0602 15:05:07.693879 140041712489280 export.py:280] warmup pass
I0602 15:05:07.765784 140041712489280 export.py:285] optimize model
I0602 15:05:07.812603 140041712489280 export.py:290] script model
I0602 15:05:07.825963 140041712489280 __init__.py:45] Registering method "encode"
I0602 15:05:07.826209 140041712489280 __init__.py:76] Testing method encode with nn~ API
I0602 15:05:07.842078 140041712489280 __init__.py:98] Testing method encode with mc.nn~ API
I0602 15:05:07.875844 140041712489280 __init__.py:118] Added method "encode" tested with buffer size 8192
I0602 15:05:07.876040 140041712489280 __init__.py:45] Registering method "decode"
I0602 15:05:07.876168 140041712489280 __init__.py:76] Testing method decode with nn~ API
I0602 15:05:07.889310 140041712489280 __init__.py:98] Testing method decode with mc.nn~ API
I0602 15:05:07.922546 140041712489280 __init__.py:118] Added method "decode" tested with buffer size 8192
I0602 15:05:07.922739 140041712489280 __init__.py:45] Registering method "forward"
I0602 15:05:07.922920 140041712489280 __init__.py:76] Testing method forward with nn~ API
I0602 15:05:07.943376 140041712489280 __init__.py:98] Testing method forward with mc.nn~ API
I0602 15:05:07.985183 140041712489280 __init__.py:118] Added method "forward" tested with buffer size 8192
I0602 15:05:07.985384 140041712489280 export.py:299] save model
Traceback (most recent call last):
  File "/content/miniconda/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/content/miniconda/lib/python3.9/site-packages/scripts/main_cli.py", line 34, in main
    app.run(export.main)
  File "/content/miniconda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/content/miniconda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/miniconda/lib/python3.9/site-packages/scripts/export.py", line 307, in main
    scripted_rave.export_to_ts(os.path.join(FLAGS.run, model_name))
  File "/content/miniconda/lib/python3.9/site-packages/nn_tilde/__init__.py", line 169, in export_to_ts
    scripted = torch.jit.script(self)
  File "/content/miniconda/lib/python3.9/site-packages/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/content/miniconda/lib/python3.9/site-packages/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/content/miniconda/lib/python3.9/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/content/miniconda/lib/python3.9/site-packages/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Module 'WasserteinScriptedRAVE' has no attribute '_attributes' (This attribute exists on the Python module, but we failed to convert Python type: 'list' to a TorchScript type. List trace inputs must have elements. Its type was inferred; try adding a type annotation for the attribute.):
  File "/content/miniconda/lib/python3.9/site-packages/nn_tilde/__init__.py", line 165
    @torch.jit.export
    def get_attributes(self):
        return self._attributes
               ~~~~~~~~~~~~~~~~ <--- HERE

```
any ideas?!

**Comment by caillonantoine** [comment]
Hi, I just found out about this issue. I'm working on a fix !

**Comment by m3da9ti** [comment]
Thanks so much, really appreciate it; plz keep me posted!

**Comment by caillonantoine** [comment]
It should be fixed now !

Use `pip install -U nn_tilde` to get the fix !

**Comment by m3da9ti** [comment]
now I get:

`Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting nn_tilde
  Downloading nn_tilde-1.5.2-py3-none-any.whl (12 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from nn_tilde) (2.0.1+cu118)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (3.12.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch->nn_tilde) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch->nn_tilde) (16.0.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch->nn_tilde) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch->nn_tilde) (1.3.0)
Installing collected packages: nn_tilde
Successfully installed nn_tilde-1.5.2
INFO:root:library loading
INFO:root:DEBUG
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpch76shel
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpch76shel/_remote_module_non_scriptable.py
I0602 16:20:56.222079 140280094282560 export.py:255] building rave
I0602 16:20:56.222857 140280094282560 resource_reader.py:50] system_path_file_exists:/content/drive/MyDrive/export/runs/test_ebfb042502/version_4/config.gin
E0602 16:20:56.223041 140280094282560 resource_reader.py:55] Path not found: /content/drive/MyDrive/export/runs/test_ebfb042502/version_4/config.gin
Traceback (most recent call last):
  File "/content/miniconda/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/content/miniconda/lib/python3.9/site-packages/scripts/main_cli.py", line 34, in main
    app.run(export.main)
  File "/content/miniconda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/content/miniconda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/miniconda/lib/python3.9/site-packages/scripts/export.py", line 257, in main
    gin.parse_config_file(os.path.join(FLAGS.run, "config.gin"))
  File "/content/miniconda/lib/python3.9/site-packages/gin/config.py", line 2457, in parse_config_file
    raise IOError(err_str.format(config_file, prefixes))
OSError: Unable to open file: /content/drive/MyDrive/export/runs/test_ebfb042502/version_4/config.gin. Searched config paths: [''].`

**Comment by m3da9ti** [comment]
Here it is:

`Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nn_tilde in /usr/local/lib/python3.10/dist-packages (1.5.2)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from nn_tilde) (2.0.1+cu118)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (3.12.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch->nn_tilde) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch->nn_tilde) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch->nn_tilde) (16.0.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch->nn_tilde) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch->nn_tilde) (1.3.0)
INFO:root:library loading
INFO:root:DEBUG
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpdmr9z67i
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpdmr9z67i/_remote_module_non_scriptable.py
I0602 18:19:13.276642 140593829475136 export.py:255] building rave
I0602 18:19:14.925714 140593829475136 export.py:280] warmup pass
I0602 18:19:15.016862 140593829475136 export.py:285] optimize model
I0602 18:19:15.068894 140593829475136 export.py:290] script model
I0602 18:19:15.085623 140593829475136 __init__.py:45] Registering method "encode"
I0602 18:19:15.085948 140593829475136 __init__.py:76] Testing method encode with nn~ API
I0602 18:19:15.104541 140593829475136 __init__.py:98] Testing method encode with mc.nn~ API
I0602 18:19:15.146568 140593829475136 __init__.py:118] Added method "encode" tested with buffer size 8192
I0602 18:19:15.146772 140593829475136 __init__.py:45] Registering method "decode"
I0602 18:19:15.146944 140593829475136 __init__.py:76] Testing method decode with nn~ API
I0602 18:19:15.164231 140593829475136 __init__.py:98] Testing method decode with mc.nn~ API
I0602 18:19:15.207143 140593829475136 __init__.py:118] Added method "decode" tested with buffer size 8192
I0602 18:19:15.207355 140593829475136 __init__.py:45] Registering method "forward"
I0602 18:19:15.207531 140593829475136 __init__.py:76] Testing method forward with nn~ API
I0602 18:19:15.233717 140593829475136 __init__.py:98] Testing method forward with mc.nn~ API
I0602 18:19:15.294027 140593829475136 __init__.py:118] Added method "forward" tested with buffer size 8192
I0602 18:19:15.294253 140593829475136 export.py:299] save model
Traceback (most recent call last):
  File "/content/miniconda/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/content/miniconda/lib/python3.9/site-packages/scripts/main_cli.py", line 34, in main
    app.run(export.main)
  File "/content/miniconda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/content/miniconda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/miniconda/lib/python3.9/site-packages/scripts/export.py", line 307, in main
    scripted_rave.export_to_ts(os.path.join(FLAGS.run, model_name))
  File "/content/miniconda/lib/python3.9/site-packages/nn_tilde/__init__.py", line 169, in export_to_ts
    scripted = torch.jit.script(self)
  File "/content/miniconda/lib/python3.9/site-packages/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/content/miniconda/lib/python3.9/site-packages/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/content/miniconda/lib/python3.9/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/content/miniconda/lib/python3.9/site-packages/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Module 'WasserteinScriptedRAVE' has no attribute '_attributes' (This attribute exists on the Python module, but we failed to convert Python type: 'list' to a TorchScript type. List trace inputs must have elements. Its type was inferred; try adding a type annotation for the attribute.):
  File "/content/miniconda/lib/python3.9/site-packages/nn_tilde/__init__.py", line 165
    @torch.jit.export
    def get_attributes(self):
        return self._attributes
               ~~~~~~~~~~~~~~~~ <--- HERE`

**Comment by caillonantoine** [comment]
You haven't installed nn tilde in the correct environment (/usr/lib instead of miniconda)

**Comment by m3da9ti** [comment]
I'm so sorry but I have no idea what you mean so I appreciate if you elaborate on what you mean...I've ran this in colab; opening a fresh colab, tried the install in the first cell (install conda, RAVE, and ffmpeg) and then ran the export cell again pointing to the directory where the last checkpoint is saved and got this error again: 
`OSError: Unable to open file: /content/drive/MyDrive/export/runs/test_ebfb042502/version_4/checkpoints/config.gin. Searched config paths: [''].`

**Comment by m3da9ti** [comment]
all good now thanks!
