### ISSUE TITLE
Batch Size, Adversarial Training

### ISSUE THREAD

**Issue by AI-Guru** [acids-ircam/RAVE#234]
Hello,

first and foremost, congratulations on RAVE! I started working with it recently and so far I am amazed! 🤗

I am training my own autoencoder on a week of data. Usually, when I train on a lot of data, I try to maximize the batch size in order to speed up training. Per default, the batch size in RAVE is 8. I could go to a good 128, the GPU did have no trouble with it.

The interesting part is as follows. Going up in batch size will finish more epochs in a shorter amount of time. It will also delay adversarial training. Adversarial training kicks in after 1M warm-up steps. This is configured using the variable phase_1_duration as defined in v1.gin.

Now, I am unsure about that. Shall I ignore batch-size maximization and stick to the default values? Should I maximize the batch size and leave the warmup as it is? Should I maximize the batch size and decrease the warm-up?

All the best,
Tristan

**Comment by robclouth** [comment]
Did you figure anything out? I'm wondering the same.

**Comment by domkirke** [comment]
Hello! Steps is the number of batches ; logically, if you increase the batch size, the number of steps for a given epoch will be reduced.  Either you adapt the duration of the warmup, or leave the value untouched (meaning that the warmup will cover a higher number of epochs).

Please not that increasing the batch size does not automatically make a better model. All the default training parameters are suited for a batch size of 8 ; we cannot provide additional support for different batch size values, train at your own risk ;)
