### ISSUE TITLE
--override PHASE_1_DURATION not processed on additional regularization config params

### ISSUE THREAD

**Issue by devstermarts** [acids-ircam/RAVE#235]
Hi @caillonantoine, overriding the duration of phase 1 using '--override PHASE_1_DURATION XXXXXX'  in V2 trainings only seems to work when using default regularization (aka with no additional --config parameter). The duration as defined in wasserstein.gin or spherical.gin seems to ignore the override option on rave train. 

Is there a way to adapt the code without manually changing the value in the .gin files while running on a Colab or Kaggle?

**Comment by caillonantoine** [comment]
Done ! The fix should be available in a few minutes :)
