### ISSUE TITLE
Error after fixing Prior bug

### ISSUE THREAD

**Issue by noiseandtechno** [acids-ircam/RAVE#237]
I should say, to begin - I'm not much of a coder and I'm just trying to train RAVE on some audio.

I experienced the bug in training prior, and replaced line 81 in train_prior.py with:

if os.name == "nt":
    num_workers = 0
else:
    num_workers = 8

However, prior still won't compile, and returns the following error:

/content/drive/MyDrive/RAVE_COLLAB
usage: train_prior.py
       [-h]
       [--resolution RESOLUTION]
       [--res-size RES_SIZE]
       [--skp-size SKP_SIZE]
       [--kernel-size KERNEL_SIZE]
       [--cycle-size CYCLE_SIZE]
       [--n-layers N_LAYERS]
       [--pretrained-vae PRETRAINED_VAE]
       [--preprocessed PREPROCESSED]
       [--wav WAV]
       [--n-signal N_SIGNAL]
       [--batch BATCH]
       [--ckpt CKPT]
       [--max-steps MAX_STEPS]
       [--val-every VAL_EVERY]
       [--name NAME]
train_prior.py: error: argument --val-every: invalid int value: '20000\\'

**Comment by caillonantoine** [comment]
It's hard to answer you without the command you actually entered, but I guess this is because you added a slash after `20000` where there should be a space, i.e. `--val-every 20000 \` instead of `--val-every 20000\`

**Comment by caillonantoine** [comment]
I'm closing this since it's about the v1 prior of rave which isn't supported anymore
