### ISSUE TITLE
Thoughts about train validation split in the current implementation

### ISSUE THREAD

**Issue by snnithya** [acids-ircam/RAVE#240]
Hi, 
This is more of suggestion than an issue. The current implementation of rave performs a train-val split only in the train.py. This is after the audio snippets from multiple files have been compiled all together in a single database (using preprocess.py). I think the train-val split should take place at a file level rather than at a sequence level which would imply splitting the audio files into train and val files and then extracting 2 databases for each set. This way there will be no leakage of sequences from one file into train and val which I think could affect training. Didn't see a discussion about this so thought I'd bring it up and hear what others think about this!

**Comment by domkirke** [comment]
Indeed, this could be a further improvement ; however, it could limit traning on a few files with long durations.
