### ISSUE TITLE
The self-reproduce audio result is bad, too smoothing

### ISSUE THREAD

**Issue by didadida-r** [acids-ircam/RAVE#251]
Hi,
I use 60 hours audio effect data to train the  Rave model, and i have try the default v2\v3\discrete model. But i find the vae model result is too smoothing, the self-reproduce result of vae is bad. Is there anything parameter i should tune. 

the discrete model training loss
![image](https://github.com/acids-ircam/RAVE/assets/13691793/6c3aa65a-7c9b-4d4d-a283-ec41054baaa1)

the v2 model training loss
![image](https://github.com/acids-ircam/RAVE/assets/13691793/6036504d-6e76-4585-810a-7724e12208d0)

here is the origin audio.
![image](https://github.com/acids-ircam/RAVE/assets/13691793/5f68b742-c9ea-43a5-a5b9-211907a19534)
the discrete vae output audio using onnx export.
![image](https://github.com/acids-ircam/RAVE/assets/13691793/59fd9cdf-73ae-433b-afe1-d0916243d6a9)
the v2 vae output audio using onnx export.
![image](https://github.com/acids-ircam/RAVE/assets/13691793/84fb127b-216f-4f25-bb02-92252a68c526)

**Comment by robclouth** [comment]
do you find that the discrete vae is more accurate? Also how did you get the onnx export working? My models just produce thin crackly noise when the libtorch one work fine
