### ISSUE TITLE
Error in colab notebook

### ISSUE THREAD

**Issue by fred-dev** [acids-ircam/RAVE#257]
Line 23 of the Resume cell of the colab notebook linked on this github repo has an error:

It is currently:
`  !/content/miniconda/bin/rave train --config $architecture --config $regularization--db_path $preprocessed_dataset --name $name --ckpt $resume --val_every 2500`

But needs to be:
`  !/content/miniconda/bin/rave train --config $architecture --config $regularization --db_path $preprocessed_dataset --name $name --ckpt $resume --val_every 2500`

(There needs to be a space after $regularization).

**Comment by domkirke** [comment]
The colab is unofficial, please address this to its author :-)
