### ISSUE TITLE
SyntaxError when parsing .gin files

### ISSUE THREAD

**Issue by asantos-6** [acids-ircam/RAVE#259]
![image](https://github.com/acids-ircam/RAVE/assets/32817093/4624af83-e4e0-4982-8a92-93a6ae0dac28)

I'm getting these errors when trying to train and I don't know why. Everything was fine and I was running the same command, but all of a sudden it stopped working. What am I missing? Any help would be appreciated!

**Comment by domkirke** [comment]
There is a problem in your .gin files ; checkout the repository ;)
