### ISSUE TITLE
ERROR: Cannot install acids-rave

### ISSUE THREAD

**Issue by SirGordon** [acids-ircam/RAVE#266]
Just installed Python on Windows and ran `pip install acids-rave`, result:

> ERROR: Cannot install acids-rave==2.1.1, acids-rave==2.1.10, acids-rave==2.1.11, acids-rave==2.1.12, acids-rave==2.1.14, acids-rave==2.1.15, acids-rave==2.1.16, acids-rave==2.1.17, acids-rave==2.1.18, acids-rave==2.1.19, acids-rave==2.1.2, acids-rave==2.1.20, acids-rave==2.1.21, acids-rave==2.1.3, acids-rave==2.1.4, acids-rave==2.1.5, acids-rave==2.1.6, acids-rave==2.1.7, acids-rave==2.1.8, acids-rave==2.1.9, acids-rave==2.2.0, acids-rave==2.2.1 and acids-rave==2.2.2 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     acids-rave 2.2.2 depends on scipy==1.10.0
>     acids-rave 2.2.1 depends on scipy==1.10.0
>     acids-rave 2.2.0 depends on scipy==1.10.0
>     acids-rave 2.1.21 depends on scipy==1.10.0
>     acids-rave 2.1.20 depends on scipy==1.10.0
>     acids-rave 2.1.19 depends on scipy==1.10.0
>     acids-rave 2.1.18 depends on scipy==1.10.0
>     acids-rave 2.1.17 depends on torch==1.13.1
>     acids-rave 2.1.16 depends on torch>=1.12.1
>     acids-rave 2.1.15 depends on torch>=1.12.1
>     acids-rave 2.1.14 depends on torch>=1.12.1
>     acids-rave 2.1.12 depends on torch>=1.12.1
>     acids-rave 2.1.11 depends on torch>=1.12.1
>     acids-rave 2.1.10 depends on torch>=1.12.1
>     acids-rave 2.1.9 depends on torch>=1.12.1
>     acids-rave 2.1.8 depends on torch>=1.12.1
>     acids-rave 2.1.7 depends on torch>=1.12.1
>     acids-rave 2.1.6 depends on torch>=1.12.1
>     acids-rave 2.1.5 depends on torch>=1.12.1
>     acids-rave 2.1.4 depends on torch>=1.12.1
>     acids-rave 2.1.3 depends on torch>=1.12.1
>     acids-rave 2.1.2 depends on torch>=1.12.1
>     acids-rave 2.1.1 depends on torch>=1.12.1
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict

What am I doing wrong?

**Comment by domkirke** [comment]
I cannot provide additional support for Windows but it seems to try installing EVERY version of rave 2.1 (that is weird), leading to conflictual dependencies. Was your python environement clean? If not, try with another environment
