### ISSUE TITLE
Number of dimensions of exported model does not agree with Tensorboard statistics

### ISSUE THREAD

**Issue by leoauri** [acids-ircam/RAVE#267]
Hi,
I am training a model with RAVE using `--config  v2 --config causal`. In tensorboard I can see, for example, that fidelity 0.8 is reached with 7 dimensions. However if I export the model with `--streaming --fidelity 0.8` and load it in `~nn model_name decode`, the component has 8 inlets. In fact all `fideltiy` settings I have tried result in an `~nn` component with some number `n^2` inlets, always a power of 2 and not agreeing with what I see in Tensorboard. 

Expected: number of inlets on ~nn component agrees with the number of dimensions needed for that fidelity as reported during training.

Am I missing something here?
Thanks,
L

**Comment by domkirke** [comment]
Yes, for export dimensions have to be a power of 2 for optimization reasons, such that the number of dimensions it is rounded up to the next power of 2.
