### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'n_channels'

### ISSUE THREAD

**Issue by masonyoungblood** [acids-ircam/RAVE#272]
When training RAVE with `--config v3` I get the following error, which was also mentioned in `#ask-for-help` on the Discord:

```
TypeError: __init__() got an unexpected keyword argument 'n_channels'
```

Just in case it is related, if I try to do training with `--config v2` I get a different error:

```
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

Do you know what the issue might be?

**Comment by domkirke** [comment]
- which RAVE version please? --n_channels is always available from v2.3. 
- Regarding the second error, what is the size of the dataset?

**Comment by chrizzlemadizzle** [comment]
Having the same error when using v2.3 in all combinations `--config v2`, `--config v3`, `--config wasserstein` and `--config spherical`. Except when using `--config default` training process is starting.

**Comment by masonyoungblood** [comment]
All of this is with v2.3. I'm working a *tiny* dataset by necessity: 100 audio files of 1-2 seconds each. I'm planning on using a different method now for this reason, but would like to figure out the first error for other projects.

**Comment by domkirke** [comment]
I will check this asap for v3. For v2, unfortunately default signal chunking in preprocessing is (2 *  131072) samples to allow random signal cropping, 131072 being the RAVE receptive fields. If you got 1-2 seconds audio files the preprocessing step will skip every file. Please consider customizing the --n_signal keyword ; however, the receptive field of the model will be reduced, so you may have to resort to the v2_short.gin configuration (that is still experimental).

**Comment by domkirke** [comment]
Bug for v3 fixed in new commit, will add a new release soon ;-)
