### ISSUE TITLE
Rave on MacOSX M2

### ISSUE THREAD

**Issue by Federico8691** [acids-ircam/RAVE#274]
Hey Axel,

does Rave works on apple silicon now as well?

Thanks!

**Comment by domkirke** [comment]
Yes

**Comment by devstermarts** [comment]
Hi Axel, does training on Apple GPUs work out of the box? I'm still running into 'Training on mac is not available yet. Use --gpu -1 to train on CPU (not recommended).' - v. 2.3.1. is installed. Torch version is 2.1.2

Thanks!
Martin

**Comment by domkirke** [comment]
This is not a problem of RAVE, this is a problem with current M2 devices that are not powerful enough to correctly train a model. But you can try :)

**Comment by devstermarts** [comment]
Not sure if I understand correctly; training on CPU is obviously senseless, but shouldn't Torch's support for MPS make training on Apple MX feasible in general? Tampering with train.py at least gets me to MPS confirmed as GPU being used, but I'm running into errors with function calls in Lightning. Anyway, will keep an eye out on that topic.
