### ISSUE TITLE
March Forum Presentation

### ISSUE THREAD

**Issue by Federico8691** [acids-ircam/RAVE#295]
Dear Axel, I just wanted to stress how the importance of having a series of full tutorials on parameter feeding, training procedures, shortcuts, and dataset preparation for Rave.
Most people in our music comunities are struggling with this absence.  We all see how for instance Somax 2 and Dicy Mubu Flucoma and other present their work in a very clear and efficient package for the final users (mostly composer, performer, and musicians in general, not scientific researcher).  Do you think something will be presented in March during the workshops? Many many thanks.

**Comment by domkirke** [comment]
Dear Federico,
you can find now tutorials on the Forum Ircam webpage (check the Readme). Some video tutorials will also arrive soon.

Thanks for your interest!
