### ISSUE TITLE
torch.nn.utils.weight_norm is deprecated

### ISSUE THREAD

**Issue by xxrraa** [acids-ircam/RAVE#304]
Hi there, upon training I get a warning that "torch.nn.utils.weight_norm is deprecated", (being used in descript_discrminator.py and blocks.py) so I switched it to the recommended torch.nn.utils.parametrizations.weight_norm.  I'm not an expert in this stuff so wondering if I should make this change, and if I should, do I need to worry about any of the points listed in the migration guide - https://pytorch.org/docs/stable/generated/torch.nn.utils.weight_norm.html
Thanks for your time

**Comment by domkirke** [comment]
Hello!
Yes, this is because RAVE has not be updated yet for latest versions of Torch ; no need to worry yet, it will be updated in a future release. Thanks!
