### ISSUE TITLE
Training colab notebook fixes proposal

### ISSUE THREAD

**Issue by aserechenko** [acids-ircam/RAVE#307]
### "Export as torchscript (.ts)" cell:

```
/content/miniconda/bin/rave export --run $model_dir --streaming --stereo --fidelity 0.999
```
Currently, this cell produces an error, that `--stereo` argument is not supported. The simplest solution is to remove this argument and run it as is.

### "Install Conda, RAVE, and ffmpeg" cell:
At a certain point this cell starts waiting for user input to confirm installation, it looks like this.
```
Proceed ([y]/n)? 
```
You need to click on the right of the `?` (there is an invisible input box here), type `y` and press Enter to continue. 

To avoid it in a future, replace `conda install ffmpeg` with `conda install -y ffmpeg`.

Anyway, I made these changes in this notebook: https://colab.research.google.com/drive/1EYfroNaoFCCqcibkDYY-P-LARFqcieyE?usp=sharing

**Comment by domkirke** [comment]
Hello, 
thanks for your comments, but this notebook is not actually maintained by acids-ircam team.... try to contact the original creator!

**Comment by aserechenko** [comment]
I could fix this notebook and provide you an updated link, to update this link in README.md.
