### ISSUE TITLE
Deactivate Beta scheduler

### ISSUE THREAD

**Issue by moiseshorta** [acids-ircam/RAVE#41]
Hi!

I've been extensively comparing both the initial RAVE version from December 2021 and the current version.
In my experiments, when training on heterogeneous datasets, I've found that the original version without the beta scheduler works quite well, whereas the new version doesn't converge as expected. The reason for this goes beyond me...

As I would like to use the new version of the code, especially the parameter to set a fixed latent space dimension, is there a way to disable the beta scheduler?

Thanks so much in advance.

**Comment by caillonantoine** [comment]
You can achieve that by passing the --min-kl .1 option to the rave training script :)

**Comment by moiseshorta** [comment]
Thanks!, no need to change --max-kl parameter? setting a --min-kl = 0.1 would fix it?
