### ISSUE TITLE
IndexError when running export_rave.py

### ISSUE THREAD

**Issue by eyesack** [acids-ircam/RAVE#47]
Getting the following error when trying to export the latent space after training RAVE:

Traceback (most recent call last):
  File "/Users/eyesack/Documents/RAVE/export_rave.py", line 202, in <module>
    RUN = search_for_run(args.RUN)
  File "/Users/eyesack/Documents/RAVE/rave/core.py", line 192, in search_for_run
    run_path = list(filter(lambda e: "last" in e, run_path))[-1]
IndexError: list index out of range

**Comment by caillonantoine** [comment]
The last version of your run doesn't have a checkpoint saved yet! You can either wait a bit or delete the last version

**Comment by eyesack** [comment]
What should I see in the checkpoint folder? I have two files in each version folder: events.out.tfevents.[bunch of numbers] and hparams.yaml.

**Comment by caillonantoine** [comment]
You should also see a checkpoint folder with several `.ckpt` files
