### ISSUE TITLE
Poor Audio Quality on Generated Files

### ISSUE THREAD

**Issue by deccolquitt** [acids-ircam/RAVE#58]
i'm struggling to train models that don't output audio with the same type of interference (best word i could think of using) on them. 

I've included a video comparing two audio tracks, both are from the same dataset, but are different rave and prior models.

file 1 is ok by my estimations, and I am getting some interesting results
file 2 however, is how the majority of my audio ends up sounding across different models, it has this 'fizzy' interference on it

what is this type of interference indicative of? how do i move past it?

https://user-images.githubusercontent.com/69871889/167447573-dbdca1e3-e327-484c-95c2-e783b590bb6e.mov

**Comment by caillonantoine** [comment]
you haven't trained the model for long enough, stage 2 hasn't started yet
