### ISSUE TITLE
Stage 2 OOM Error

### ISSUE THREAD

**Issue by iamzoltan** [acids-ircam/RAVE#59]
once I train models for the full 1M steps, and it enters the adversarial training, It stops and I end up getting this error:

` 
File "/home/user/code/RAVE/env3.9/lib/python3.9/site-packages/torch/nn/functional.py", line 4364, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 130.00 MiB (GPU 1; 7.93 GiB total capacity; 6.96 GiB already allocated; 73.62 MiB free; 7.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

I have tried setting this variable, among other solutions, but I am at a loss.

any ideas?

**Comment by caillonantoine** [comment]
You should decrease the batch size, stage 2 is way more RAM intensive

**Comment by iamzoltan** [comment]
I just tried a small model with a smaller batch size. training is much quicker so lets see if this works. Thanks for your help
