### ISSUE TITLE
Error Exporting Converted Rave Model

### ISSUE THREAD

**Issue by iamzoltan** [acids-ircam/RAVE#60]
when trying to export a model, after running the conversion script, I now get the following error:

```
[1394.96] script model
Traceback (most recent call last):
  File "/home/user/code/RAVE/export_rave.py", line 245, in <module>
    model = TraceModel(model, resample, args.FIDELITY)
  File "/home/user/code/RAVE/export_rave.py", line 70, in __init__
    latent_size = 2**math.ceil(math.log2(latent_size))
ValueError: math domain error
```

any suggestions?

**Comment by caillonantoine** [comment]
I have seen this error before without being able to track it down. If I'm correct, the estimated latent space dimensionality is 0 for this run, isn't it ?

**Comment by iamzoltan** [comment]
exporting the smaller converted model works :)
