### ISSUE TITLE
Freeze when sanity checking dataloader before training prior

### ISSUE THREAD

**Issue by weyesnob** [acids-ircam/RAVE#63]
I'm running into issues when training the prior. Stage 1 of training went fine but when I run train_prior.py with the command generated by the CLI helper my console freezes when trying to sanity check the dataloader. 

I had to set `num_workers=0` when initializing the train and validation DataLoader, otherwise I would be running into a TypeError "Cannot pickle 'Environment' object".

Here's what the CLI looks like upon running the command:
```GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name             | Type                  | Params
-----------------------------------------------------------
0 | diagonal_shift   | DiagonalShift         | 0
1 | quantized_normal | QuantizedNormal       | 0
2 | synth            | RecursiveScriptModule | 17.6 M
3 | pre_net          | Sequential            | 49.7 K
4 | residuals        | ModuleList            | 19.7 M
5 | post_net         | Sequential            | 74.5 K
-----------------------------------------------------------
37.4 M    Trainable params
0         Non-trainable params
37.4 M    Total params
149.707   Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]D:\Anaconda3\envs\rave\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:240: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Sanity Checking DataLoader 0:   0%|                                                                                                                                               | 0/2 [00:00<?, ?it/s] ```
```
The console then stops reacting, not even to Ctrl+C. Disabling the sanity checks by passing `num_sanity_val_steps=0` into the trainer initialization leads to a freeze right before starting training. I'm not sure why this is happening, any help would be greatly appreciated.

A bit more information about my system:
Windows 10
CUDA 11.3
NVIDIA RTX2060
pytorch 1.11.0 build py3.9_cuda11.3_cudnn8_0
pytorch-lightning 1.6.1
Let me know if there is any other information I can supply you with.

**Comment by weyesnob** [comment]
I've spent some time looking at the script inside the debugger, and it seems like the program flow passes `Model.encode()` exactly twice before getting stuck in tdqm's `TMonitor.run()` method. This happens regardless of whether I bypass the DataLoader sanity check or not.

**Comment by caillonantoine** [comment]
It's gonna be hard for me to track the bug down as I can't really reproduce it... Have you checked that your GPU has enough RAM ?

**Comment by weyesnob** [comment]
Yes, RAM doesn't seem to be the issue. I managed to find a minimal code example that causes the freeze. The issue seems to be pytorch-related and I have raised an issue over there. I'll post again once there is an update.

**Comment by weyesnob** [comment]
I'll close this for now, as the issue on pytorch takes some time to be resolved.

I managed to circumvent the problem by moving the training process over to the WSL.
