### ISSUE TITLE
Reaching 1M Steps

### ISSUE THREAD

**Issue by deccolquitt** [acids-ircam/RAVE#64]
I am training two separate models and by my calculations should've reached 1M steps in both, but the output of my training has given me no indication of this at all. 

One of my models outputs the following whilst training:

```
Epoch 10529: 100% 113/113 [14:53<00:00, 297.89s/it, v_num=4]
Epoch 10619:  88% 100/113 [59:28<-2:42:41, -0.00it/s, v_num=4]
Validation: 0it [00:00, ?it/s]
Validation DataLoader 0:   0% 0/3 [00:00<?, ?it/s]
```

and the other:

```
Epoch 2279:  98% 505/516 [00:00<?, ?it/s]
Epoch 2287:  51% 260/505 [05:24<-1:54:36, -0.75it/s, v_num=3]

```
by my calculations, 10529 epochs with 113 steps per epoch = 1,189,777
and 2279 x 505 = 1,150,895

could you shine anymore light on when I might 1M steps if I have not met them already (as I said before, I have had absolutely no indication in my models output that this has happened)

**Comment by caillonantoine** [comment]
Use `tensorboard --logdir runs --bind_all` to monitor your run !
