### ISSUE TITLE
fb distance

### ISSUE THREAD

**Issue by faroit** [acids-ircam/RAVE#74]
👋 @caillonantoine really great work!

As in understand from the paper there is a multiband loss computed within the fb domain...

<img width="893" alt="image" src="https://user-images.githubusercontent.com/72940/170259051-b6210995-d61b-4e39-9a27-9a72df5f8763.png">

Looking at the code however you also have the end2end mrstft loss in stage1....

https://github.com/acids-ircam/RAVE/blob/9539ef00225716bd205409885db318f75bba72de/rave/model.py#L588-L589

is that correct? did do an ablation study on the impact of this?

**Comment by caillonantoine** [comment]
Hi, the full band spectral distance is important to reduce the artifacts produced by the inverse pqmf !
