### ISSUE TITLE
training data for rave and prior problem

### ISSUE THREAD

**Issue by meadow163** [acids-ircam/RAVE#76]
caillonantoine,

1.  I have only 50 hours background music data, and I used it to train RAVE model, I have 8 GPU and I used 8 GPU to train, so I 'm not sure if I can set 'BATCH=256', can I use this such batch size? Does it will affect the quality of wav reconstruction ? I saw your default is 8.

2.  Cause I have no other music data, Can I also use this 50 hours data to train the prior model?

Best,

**Comment by caillonantoine** [comment]
1. For now I don't support multi GPU training ! Some persons have tried to do it and apparently there is a problem with either the dataloading system or pytorch lightning.

2. yes ! actually you even should use the same dataset for both rave and the prior model.
