### ISSUE TITLE
train_rave.py does not recognise GPU

### ISSUE THREAD

**Issue by iorhythm** [acids-ircam/RAVE#78]
Hey there,

it seems that the train_rave.py script (more specifically pytorch lightning) can't find my system's GPU.

A few machine specs:
- Win 10 Pro
- RTX 3060

Steps:
1. Downloaded this repository
2. Created a new env using miniconda
3. Installed pip, then installed all RAVE dependencies
4. Ran cli_helper.py
5. Tried to call train_rave.py as per cli_helper's output - I'm getting the following error:
```pytorch_lightning.utilities.exceptions.MisconfigurationException: GPUAccelerator can not run on your system since the accelerator is not available. The following accelerator(s) is available and can be passed into `accelerator` argument of `Trainer`: ['cpu'].```

Any ideas?

Thanks in advance.

**Comment by caillonantoine** [comment]
What is the output of `python -c "import torch; print(torch.cuda.is_available())"` ?

**Comment by iorhythm** [comment]
False

Running `nvidia-smi` shows the GPU just fine btw

**Comment by caillonantoine** [comment]
I can't help you with that, maybe ask a question on the pytorch repo !

**Comment by aidanswank** [comment]
@iorhythm I have same specs and error, have you found a solution by any chance? Thanks

**Comment by iorhythm** [comment]
> @iorhythm I have same specs and error, have you found a solution by any chance? Thanks

Hey @aidanswank sorry for the delay - no I haven't unfortunately. If I come across anything I'll post here.

**Comment by nshaheed** [comment]
I ran into this issue, what fixed it for me was installing pytorch using the command given by [pytorch ](https://pytorch.org/get-started/locally/) on their website rather than installing pytorch via pip or conda
