### ISSUE TITLE
Issues training prior from low capacity rave

### ISSUE THREAD

**Issue by xyzalanix** [acids-ircam/RAVE#80]
Hi @caillonantoine !
I've trained a rave model with `capacity=5`, `configuration small` and having trouble training prior:

`RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same`

Is there anything I should change in my train_prior command that would suit my low capacity .ts?

**Here's my rave config:**
```
data_size: 16
capacity: 5
latent_size: 128
ratios:
- 4
- 4
- 4
- 2
bias: true
loud_stride: 1
use_noise: true
noise_ratios:
- 4
- 4
- 4
noise_bands: 5
d_capacity: 16
d_multiplier: 4
d_n_layers: 4
warmup: 1
mode: hinge
no_latency: false
min_kl: 0.1
max_kl: 0.1
cropped_latent_size: 0
feature_match: true
sr: 48000
```

**Comment by caillonantoine** [comment]
Hi, this is a preprocessing problem that should be fixed in e586ed5 !
